#==============================================================================
# type: StorageClass
# description: Storage class for amazon ebs resource
#==============================================================================
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: tech-challenge-7soat-ebs-storage-class
provisioner: ebs.csi.aws.com
parameters:
  type: gp2
  fsType: ext4
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
