apiVersion: v1
kind: Service
metadata:
  name:  tech-challenge-7soat-service-db
spec:
  type: ClusterIP
  selector:
    app: tech-challenge-7soat-statefulset-db
  ports:
  - port:  5432
    targetPort: 5432