apiVersion: apps/v1
kind: Deployment
metadata:
  name: tech-challenge-7soat-grafana-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tech-challenge-7soat-grafana
  template:
    metadata:
      labels:
        app: tech-challenge-7soat-grafana
    spec:
      containers:
      - name: tech-challenge-7soat-grafana
        image: grafana/grafana:latest
        ports:
        - containerPort: 3000
        volumeMounts:
        - name: grafana-storage
          mountPath: /var/lib/grafana
          subPath: grafana
        - name: grafana-config
          mountPath: /etc/grafana/grafana.ini
          subPath: grafana.ini
      volumes:
      - name: grafana-storage
        emptyDir: {}
      - name: grafana-config
        configMap:
          name: tech-challenge-7soat-grafana-config-map
