apiVersion: v1
kind: Service
metadata:
  name: tech-challenge-7soat-grafana-service
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: tech-challenge-7soat-grafana
