apiVersion: v1
kind: ServiceAccount
metadata:
  name: cluster-autoscaler
  namespace: kube-system
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::839260668425:role/eksctl-tech-challenge-7soat-addon-iamservicea-Role1-jmmbHXhcH9df
