apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tech-challenge-7soat-prometheus-cluster-role
  labels:
    app: tech-challenge-7soat-prometheus-cluster-role
rules:
  - apiGroups: [""]
    resources: ["nodes", "pods", "endpoints", "services", "nodes/proxy"]
    verbs: ["list", "watch", "get"]
  - apiGroups: ["extensions", "apps"]
    resources: ["deployments", "replicasets", "statefulsets"]
    verbs: ["list", "watch", "get"]
