apiVersion: v1
kind: Service
metadata:
  name: tech-challenge-7soat-prometheus-service
spec:
  type: ClusterIP
  ports:
    - port: 9090
      targetPort: 9090
  selector:
    app: tech-challenge-7soat-prometheus
