apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    events {}

    stream {
        upstream rds_backend {
            server <rds_backend_url_here>:5432;
        }

        server {
            listen 55432;

            proxy_pass rds_backend;
            proxy_timeout 10s;
            proxy_connect_timeout 10s;
        }
    }
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-rds-proxy
spec:
  containers:
    - name: nginx
      image: nginx:latest
      ports:
        - containerPort: 55432
      volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
  volumes:
    - name: nginx-config
      configMap:
        name: nginx-config
