apiVersion: v1
kind: Service
metadata:
  name: tech-challenge-7soat-api-np
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 32000
      targetPort: 3000
  selector:
    app: tech-challenge-7soat-api