apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: tech-challenge-7soat-payments-service-external-secret
  namespace: default
spec:
  refreshInterval: 72h
  secretStoreRef:
    name: tech-challenge-7soat-external-secret-store
    kind: SecretStore
  data:
  - secretKey: ENVIRONMENT
    remoteRef:
      key: 7Soat
      property: ENVIRONMENT
  - secretKey: DATABASE_URL
    remoteRef:
      key: 7Soat
      property: PAYMENTS_SERVICE_DATABASE_URL
  - secretKey: MERCADO_PAGO_ACCESS_TOKEN
    remoteRef:
      key: 7Soat
      property: MERCADO_PAGO_ACCESS_TOKEN
  - secretKey: MERCADO_PAGO_SECRET
    remoteRef:
      key: 7Soat
      property: MERCADO_PAGO_SECRET
  - secretKey: AWS_ACCESS_KEY_ID
    remoteRef:
      key: 7Soat
      property: AWS_ACCESS_KEY_ID
  - secretKey: AWS_SECRET_ACCESS_KEY
    remoteRef:
      key: 7Soat
      property: AWS_SECRET_ACCESS_KEY
  - secretKey: AWS_REGION
    remoteRef:
      key: 7Soat
      property: AWS_REGION
  - secretKey: PAYMENTS_SNS_TOPIC_ARN
    remoteRef:
      key: 7Soat
      property: PAYMENTS_SNS_TOPIC_ARN
  - secretKey: PAYMENTS_API_KEY
    remoteRef:
      key: 7Soat
      property: PAYMENTS_API_KEY
