apiVersion: v1
kind: Service
metadata:
  name: tech-challenge-7soat-payments-service-cluster-ip
spec:
  selector:
    app: tech-challenge-7soat-payments-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP
