apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: tech-challenge-7soat-orders-service-external-secret
  namespace: default
spec:
  refreshInterval: 72h
  secretStoreRef:
    name: tech-challenge-7soat-external-secret-store
    kind: SecretStore
  data:
  - secretKey: PAYMENTS_API_BASE_URL
    remoteRef:
      key: 7Soat
      property: PAYMENTS_API_BASE_URL
  - secretKey: PAYMENTS_API_KEY
    remoteRef:
      key: 7Soat
      property: PAYMENTS_API_KEY
  - secretKey: PRODUCTS_CATALOG_API_BASE_URL
    remoteRef:
      key: 7Soat
      property: PRODUCTS_CATALOG_API_BASE_URL
  - secretKey: PRODUCTS_CATALOG_API_KEY
    remoteRef:
      key: 7Soat
      property: PRODUCTS_CATALOG_API_KEY
  - secretKey: AWS_ACCESS_KEY_ID
    remoteRef:
      key: 7Soat
      property: AWS_ACCESS_KEY_ID
  - secretKey: AWS_SECRET_ACCESS_KEY
    remoteRef:
      key: 7Soat
      property: AWS_SECRET_ACCESS_KEY
  - secretKey: AWS_REGION
    remoteRef:
      key: 7Soat
      property: AWS_DEFAULT_REGION
  - secretKey: ORDERS_SQS_QUEUE_URL
    remoteRef:
      key: 7Soat
      property: ORDERS_SQS_QUEUE_URL
  - secretKey: COGNITO_USER_POOL_ID
    remoteRef:
      key: 7Soat
      property: COGNITO_USER_POOL_ID
