apiVersion: apps/v1
kind: Deployment
metadata:
  name: tech-challenge-7soat-orders-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tech-challenge-7soat-orders-service
  template:
    metadata:
      labels:
        app: tech-challenge-7soat-orders-service
    spec:
      containers:
      - name: tech-challenge-7soat-orders-service
        image: 839260668425.dkr.ecr.us-east-1.amazonaws.com/tech-challenge-7soat/orders-service:latest
        resources:
          limits:
              memory: "512Mi"
              cpu: "500m"
        ports:
          - containerPort: 3000
            name: http
        envFrom:
            - secretRef:
                name: tech-challenge-7soat-orders-service-external-secret
        readinessProbe:
          httpGet:
            path: /metrics
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 15
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /metrics
            port: 3000
          initialDelaySeconds: 20
          periodSeconds: 30
