apiVersion: v1
kind: Service
metadata:
  name: tech-challenge-7soat-orders-service-lb
spec:
  selector:
    app: tech-challenge-7soat-orders-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer