apiVersion: v1
kind: Service
metadata:
  name: tech-challenge-7soat-api-lb
spec:
  selector:
    app: tech-challenge-7soat-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer