apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: tech-challenge-7soat-products-catalog-service-external-secret
  namespace: default
spec:
  refreshInterval: 72h
  secretStoreRef:
    name: tech-challenge-7soat-external-secret-store
    kind: SecretStore
  data:
  - secretKey: ENVIRONMENT
    remoteRef:
      key: 7Soat
      property: ENVIRONMENT
  - secretKey: DATABASE_URL
    remoteRef:
      key: 7Soat
      property: PRODUCTS_CATALOG_SERVICE_DATABASE_URL
  - secretKey: PRODUCTS_CATALOG_API_KEY
    remoteRef:
      key: 7Soat
      property: PRODUCTS_CATALOG_API_KEY
