name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.7

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Initialize Terraform
        run: terraform init
        working-directory: .

      - name: Validate Terraform
        run: terraform validate
        working-directory: .

    #   - name: Plan Terraform
    #     run: terraform plan
    #     working-directory: .
    #     env:
    #       TF_VAR_aws_region: ${{ secrets.AWS_REGION }}

    #   - name: Apply Terraform
    #     run: terraform apply -auto-approve
    #     working-directory: .
    #     env:
    #       TF_VAR_aws_region: ${{ secrets.AWS_REGION }}